[versions]

coreVersion = "1.17.0"
kotlin = "2.3.0"
compose = "1.10.0"
agp = "8.13.2"
androidx-activityCompose = "1.12.2"
kotlinxCoroutinesCore = "1.10.2"
core = "1.7.0"
kpermissions = "2.0.1"
material3 = "1.10.0-alpha05"
runtime = "1.10.0"
startupRuntime = "1.2.0"
ktor = "3.3.3"
maven-publish = "0.35.0"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreVersion" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
core = { module = "androidx.core:core", version.ref = "coreVersion" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kpermissions-notification = { module = "io.github.the-best-is-best:kpermissions-notification", version.ref = "kpermissions" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
the-best-is1-best-kpermissions-core = { module = "io.github.the-best-is-best:kpermissions-core", version.ref = "kpermissions" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
#hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
